# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12
  - PG_SUPPORTED_VERSIONS=13
  - PG_SUPPORTED_VERSIONS=14
  - PG_SUPPORTED_VERSIONS=15

language: C
dist: xenial

arch:
  - AMD64
  - ppc64le

before_install:
  - sudo apt-get update -qq

install:
  # upgrade postgresql-common for new apt.postgresql.org.sh
  - sudo apt-get install -y postgresql-common
  - sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -p -v $PG_SUPPORTED_VERSIONS -i

script:
  - make
  - sudo make install
  - pg_virtualenv make installcheck
  - if test -s regression.diffs; then cat regression.diffs; fi
